# Generated by Django 4.1.7 on 2023-02-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('seats', models.IntegerField()),
                ('rows', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Зали',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Фільм',
                'verbose_name_plural': 'Фільми',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('time', models.CharField(max_length=10)),
                ('user_email', models.EmailField(blank=True, max_length=50)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie.hall')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie.movie')),
            ],
            options={
                'verbose_name': 'Квиток',
                'verbose_name_plural': 'Квитки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie.hall')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie.movie')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеанси',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('content', models.TextField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie.movie')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
    ]
