# Generated by Django 4.1.7 on 2023-02-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.IntegerField(default=150),
        ),
    ]
