# Generated by Django 4.1.7 on 2023-03-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_session_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='raw',
            new_name='row',
        ),
    ]
