# Generated by Django 4.1.7 on 2023-03-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_raw_ticket_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
